### ISSUE TITLE
Component: Expandable region

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#10]
- [ ] HTML/CSS component
- [ ] Web Component
- [ ] Figma component
- [ ] Design tokens
- [ ] Documentation

**Comment by usethetics** [comment]
First version of Figma Collapse/expand component available here: https://www.figma.com/file/gqQhMe3gj4YlC6JrZOWiCv/Components?node-id=102%3A169

**Comment by usethetics** [comment]
Needs expanded and contracted icons.

**Comment by Yolijn** [comment]
This component needs more rationale. Is it one single accordion (details/summary) or is it the read-more button that shows more of some text-content?

**Comment by Robbert** [comment]
Als onderdeel van spring cleaning (nl-design-system/kernteam#600) gesloten. Dit is een te algemeen concept, we gaan verder met specifiekere componenten zoals Details (#218)
