### ISSUE TITLE
Documentation: Interaction flows

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#105]
As a user I want a consistent interaction flow.

In a login flow, for instance, I want to have the same ‘interaction direction’ as in a form flow. If, in a login flow I input my credentials to the left and submit them with a button placed to the right, while in a form I enter data with a submit button placed below the form to the left this goes against my expectation. This inconsistency might confuse me as a user and have a negative impact on the trust I have in the quality of the product.

**Comment by Yolijn** [comment]
Bij de richtlijn om alle componenten altijd aan het begin van de tekst uit te lijnen is deze documentatie niet meer relevant. Buttons zullen in nederlandse pagina's altijd links worden uitgelijnd op deze manier
