### ISSUE TITLE
Component: CAPTCHA

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#123]

**Comment by usethetics** [comment]
Remarks from @macedvisioned from the form guidelines:

> (bij voorkeur Recaptcha versie 3 of een Honeypot validatie. Er wordt dan op de achtergrond gecontroleerd of het e-mailadres van de gebruiker valide is en niet voorkomt in spamblockers.

**Comment by Robbert** [comment]
@macedvisioned No preference yet, we are waiting for community contributions from teams that successfully use an accessible captcha that is open source and reusable for others.
