### ISSUE TITLE
Component: Number input

### ISSUE THREAD

**Issue by macedvisioned** [nl-design-system/backlog#125]
Use when a user can only insert a numeric value

## Code

We won't use the HTML standard `<input type="number">` as this might cause issues for users.
Based on the decisions made by [the GOV.UK Design System team](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) we will use 
```html
<input type="text" inputmode="numeric" pattern="[0-9]*"/>
```

**Comment by usethetics** [comment]
Might be interesting to include or mention in our guidelines:
[Why the GOV.UK Design System team changed the input type for numbers](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)
