### ISSUE TITLE
Web Components can be used in React

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#13]
Some projects use NL Design System inside React projects.

Since Web Components are the foundation of the NL Design System components, these components should be usable in the latest stable release of React. Currently that is [version `^17.0.0`](https://reactjs.org/blog/2020/10/20/react-v17.html).

We are looking for feedback from the community to gather the requirements.

Current considerations:

- [ ] should web components be wrapped in React components?
- [ ] documentation on how to use NL Design System components in React projects
- [ ] how to automate testing the integration of NL Design System with React?
- [ ] how to support lazy loading of components in React?

**Comment by JeroenReumkens** [comment]
@dvens I think this is right in your alley? Perhaps you want to advice them / guide them in the right direction 😁
