### ISSUE TITLE
Component: Language switcher

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#140]

**Comment by Yolijn** [comment]
@Robbert Jeffrey and I would like to brainstorm about this component further before adding it to the index (again). 

Thoughts:
- link for url-changes
- button for content-changes
- what about switching when many languages are available?
- what about the [google-translate options Den Haag is currently thinking about](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?type=design&node-id=16094-113240&t=ZfGynXrEwdQpFY7W-4)?

**Comment by Yolijn** [comment]
We gaan in plaats `language-navigation-as-button` gebruiken https://github.com/nl-design-system/backlog/issues/243
