### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#15]
We should provide a definition of done to share the needs of the community and end-users with contributors.

- [ ] The document is available as `DEFINITION_OF_DONE.md` in this repository.
- [ ] Specific variants for the Definition of Done are available as checklist template for pull requests in the code repository.

**Comment by usethetics** [comment]
@Robbert From you point of view, would you combine definitions of done for developers and designers in a single file or split these up into two separate ones?

**Comment by JeroenduC** [comment]
![image](https://user-images.githubusercontent.com/49227194/123402261-d71a1e80-d5a7-11eb-96dc-f34071791877.png)
