### ISSUE TITLE
Paragraph in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#161]
Gebaseerd op `utrecht-paragraph`.

Design tokens: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-paragraph-tokens--page

Varianten:

- _Lead paragraph_ is veel gebruikt
- _Small print_ hoeft nog niet, die is experimenteel

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/115
