### ISSUE TITLE
Ordered list in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#162]
Gebaseerd op `utrecht-unordered-list`.

https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-unordered-list--default-story

Bij Utrecht is er nog geen goed ontwerp voor geneste lijsten, en geen goede design tokens voor geneste lijsten.

Opsommingen met a/b/c en i/ii/iii etcetera zou ik alleen willen aanbieden wanneer we richtlijnen hebben voor wanneer je welke moet kiezen.

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/117
