### ISSUE TITLE
Separator in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#163]
Gebaseerd op de [`utrecht-separator` component](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-separator--default-story)

De separator is bedoeld om door een scheiding content te groeperen. De separator wordt aangekondigd door screen readers.

Den Haag heeft een [`denhaag-divider` component](https://nl-design-system.github.io/denhaag/?path=/story/react-data-display-divider--default-story), maar die is _presentational_.

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/119
