### ISSUE TITLE
Link in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#164]
Gebaseerd op de [`utrecht-link` component](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-link--default-story)

De volgende interactieve states:

- `active` (pointer ingedrukt)
- `hover`
- `focus` focus state, geen focus ring
- `focus-visible`: focus state + focus ring

Variant:

- Placeholder link. Bijvoorbeeld naar een stap verderop in het formulier die nog niet geopend mag worden. Of voor een "Vorige" link op pagina 1.

Varianten voor later:

- Link met icon. Hiervoor moet met front-end devs een betere variant uitgewerkt worden.
- Image link: image met focus ring
- Article link: card met hover / focus / focus visible

Varianten die misschien niet nodig zijn in Figma:

- E-mail link: nauwelijks zichtbaar verschil, niet de moeite in Figma?
- External link: we gaan niet standaard een icon toevoegen.

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/118
