### ISSUE TITLE
Data list in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#165]
Niet "Definition list", een termen-lijst component hebben we nog niet. We hebben alleen de data opsomming voor in formulieren en dashboards.

Gebaseerd op de [`utrecht-data-list` component](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-data-list--default-story). Die heeft echter alleen een variant zonder kolommen.

De variant met kolommen kun je overnemen van de [Den Haag Description list component in Figma](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Den-Haag-Design-System?node-id=8487%3A27946&t=lAO3J4ggRFOEhvJ8-4).

**Comment by Yolijn** [comment]
Figma duplicate of https://github.com/nl-design-system/backlog/issues/185
