### ISSUE TITLE
Component: Inline quotation

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/backlog#184]
The HTML `q` element is used for inline quotations. It allows us to make use of the `cite` attribute.

NB. According to the WHATWG spec:
The use of q elements to mark up quotations is entirely optional; using explicit quotation punctuation without q elements is just as correct. Do we need to add it?

**Comment by Yolijn** [comment]
@Robbert what do you think, can we close this issue and only add it when the need arises?

**Comment by Robbert** [comment]
Agreed.
