### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/backlog#186]
## Naam

Legend

[Link naar GitHub Discussion](https://github.com/orgs/nl-design-system/discussions/279)

---

## Notities

When using a #124 one can use the `Legend` component. It might have a `heading-x` as a child element.

**Comment by Robbert** [comment]
Wat mij betreft kan deze onderdeel zijn van de fieldset component (#124), het één kan niet zonder het ander bestaan denk ik.
@Yolijn: kunnen we deze sluiten?

**Comment by Yolijn** [comment]
@Robbert Wil je het component dan `fieldset-legend` noemen of wil je het component helemaal niet aanbieden? Tot nog toe hebben we ook componenten als `form-field-label` wel toegevoegd.

**Comment by Robbert** [comment]
Inderdaad @Yolijn — In HTML zie ik niet in hoe je een legend los kan zien van de fieldset, zou het wel een los component moeten zijn? @rianrietveld Kopjes in formulieren, daar gaan we richtlijnen over aanbieden. Naast fieldset + legend, is er überhaupt een acceptabele aanpak van kopjes in formulieren?

Als er wel een goede aanpak is, dan moeten we misschien legend hernoemen naar "Form heading" ofzo, om niet de verwarring te wekken met het `<legend>` element dat niet zonder `<fieldset>` kan bestaan.

**Comment by rianrietveld** [comment]
@Yolijn 
@Robbert 
Mee eens dat legend hoort bij fieldset en geen losse component is.
MDN: The <legend> [`HTML`](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a caption for the content of its parent [`<fieldset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset).

Een legend kan een kopje bevatten.

Kopjes buiten legends in formulieren wil ik vermijden. Alle info in een formulier moet aan een interactief element gekoppeld zijn. Losse kopjes is leuk voor de zichtbare structuur, maar de kans bestaat dat screenreadergebruikers ze missen in 'form-mode'.

Legends in een fieldset kunnen dienen als kopjes binnen een formulier.
Is dit niet mogelijk, gebruik dan een meerstappen formuier.
Voorbeeld van een legend ipv een kopje
```
<fieldset>
<legend><h3>Uw gegevens</h3></legend>
  <label for="voornaam"><input id="voornaam">
  <label for="achternaam"><input id="achternaam">
  <label for="email"><input id="email">
<fieldset>
```
Voordeel is dat bij elk inputveld binnen een fieldset, de legend wordt herhaald, waardoor het duidelijk is bij welk onderwerp een inputveld hoort.
Handig als het een billing vs shipping adres betreft.

**Comment by Robbert** [comment]
We gaan geen losse component maken.
