### ISSUE TITLE
Design tokens Figma library

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#20]
A separate Figma library that houses all design tokens for the white-label theme. This library can be used as a starting point for other themes, new and translations of existing organisation brand styles.

- [ ] Figma library with component setup and Design Token plugin
- [ ] Connection between tokens in Figma and GitHub for code
- [ ] Documentation on getting started with the Figma library
- [ ] Documentation on getting started with Design Tokens
- [ ] Discuss when a Figma component should be added, in the community or candidate state?
  - [ ] Add creation of a Figma component to the Definition of Done for components

**Comment by Yolijn** [comment]
- [ ] Figma library with component setup and Design Token plugin
- [ ] Connection between tokens in Figma and GitHub for code
- [ ] Documentation on getting started with the Figma library
- [ ] Documentation on getting started with Design Tokens
- [ ] Add creation of a Figma component to the DoD of a community(?) component

**Comment by Yolijn** [comment]
#193
