### ISSUE TITLE
Component: Language Switcher

### ISSUE THREAD

**Issue by Anton-Olivier** [nl-design-system/backlog#244]
We willen graag meer leren over het Language Switcher component. In welke vorm, of vormen, wordt deze momenteel ingezet en toegepast binnen jouw organisatie?

Deel hieronder een link naar Figma, Storybook of screenshots. Met deze informatie kunnen we bewijzen dat het component onderdeel moet worden van de NL Design System component library.

Daarnaast wordt het delen van onderzoek gewaardeerd. Dus heb je zelf onderzoek gedaan en zijn er inzichten voor dit component? Dan horen we dit ook graag!

[Link naar bericht in Slack]
_To be added_

---

**Naam**
Language switcher

**Doel**
Het veranderen van de taal van de website.

**Gerelateerde componenten**
_onbekend_

**Onderzoek**

[6 Tips for Improving Language Switchers on Ecommerce Sites - Nielsen Norman Group](https://www.nngroup.com/articles/language-switching-ecommerce/)
Artikel met tips voor het Language switcher component op e-commerce sites. De meeste tips zijn ook bruikbaar voor overheidssites. Deze informatie komt ook terug in een [bijbehorende video](https://www.nngroup.com/videos/language-switchers/).

**Comment by Anton-Olivier** [comment]
Fout opgevoerd als issue ipv bedoelde discussion.

**Comment by Robbert** [comment]
Duplicate of #243 and discussion https://github.com/orgs/nl-design-system/discussions/245

Thanks for starting the discussion!
