### ISSUE TITLE
Pre-heading

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#246]
## Naam

Pre-heading

[Link naar GitHub Discussion](https://github.com/orgs/nl-design-system/discussions/286)

**Comment by Rozerinay** [comment]
We sluiten de Discussion voor deze component, omdat deze niet langer een zelfstandige component is maar onderdeel uitmaakt van de [Heading Group](https://github.com/orgs/nl-design-system/discussions/323).
