### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#4]
The project would benefit from having a code of conduct, to provide a safe environment for everyone to contribute.

Based on the choice for the Contributor Covenant by the COVID-19 project, I decided to go for that as well. Their document is based on the version 1.4.

https://github.com/minvws/nl-covid19-notification-app-website/blob/43e668103e8d674a15c9e9bfccff9d3f31999b6f/CODE_OF_CONDUCT.md

 Version 2.0 provides some structure to have consequences for code of conduct violations, which seemed essential to me. This is the main reason I chose to go for that. @usethetics found out there is no Dutch translation for version 2.0. This means making the choice:

- providing no Dutch translation
- using v1.4 in Dutch and v2.0 in English side by side
- make an effort to translate v2.0 to Dutch
- switch to v1.4 so we can have Dutch and English with the same content.

For now, the status quo is v1.4 in Dutch and v2.0 in English.

An open question is: where do we need to make mention of the code of conduct?

---

Current status:

- [x] The Code of Conduct is named `CODE_OF_CONDUCT.md` so it can be detected by Github and linked from the interface automatically
- [x] Choose a template for the Code of Conduct
- [x] Include the Code of Conduct in the GitHub repository
- [ ] Give the Code of Conduct visibility in Slack
- [ ] Provide a Dutch translation for the latest Contributor Covenant v2.0
- [ ] Add Code of Conduct to the GitHub organisation overview

**Comment by usethetics** [comment]
> For now, the status quo is v1.4 in Dutch and v2.0 in English.

In due time we can ask the community to provide a proper translation of v2.0 to Dutch. We should make sure to also contribute the translation to the Contributor Covenant.

**Comment by usethetics** [comment]
> An open question is: where do we need to make mention of the code of conduct?

The code of conduct should be visible of each and every touchpoint where we expect people to contribute. For now that would mean that we should likely place a link in our Slack channel(s) and visibly in the footer of the design system documentation site.
