### ISSUE TITLE
Component: Frequently asked questions (FAQs)

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#57]
- [ ] HTML/CSS component
- [ ] Web Component
- [ ] Figma component
- [ ] Design tokens
- [ ] Documentation

# Description
A component that displays common questions and their answers. Generally in a format where the question triggers an expansion panel displaying the accompanying answer.

## Related
- [Collapse/Expand](https://github.com/nl-design-system/backlog/issues/10)

**Comment by usethetics** [comment]
Related:

- [Collapse/Expand](https://github.com/nl-design-system/backlog/issues/10)

**Comment by usethetics** [comment]
This is arguably an Accordion component…

**Comment by Yolijn** [comment]
I don't think this is actually a component. And as per the research of Amsterdam, we might not even want a common pattern for it https://www.amsterdam.nl/schrijfwijzer/structuur-heldere-tekst/structuur-heldere-webtekst/voorkom-webpagina-gestelde-vragen/

**Comment by Yolijn** [comment]
@usethetics I suggest closing this issue, what do you think?

**Comment by usethetics** [comment]
@Yolijn Good call, let’s close this issue. Interface and content should be (as) self-explanatory (as possible) and FAQs should be discouraged.
