### ISSUE TITLE
Group: List

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#58]
- [ ] HTML/CSS component
- [ ] Web Component
- [ ] Figma component
- [ ] Design tokens
- [ ] Documentation

# Description
Lists display related information.

## Variations
- Unordered (bulleted) list
- Ordered list
- Definition list

An ordered list displays information in a sequential manner. A definition list displays a definition term and its description.

## Use when
- Use lists to group related information

## Related
- [Table component](https://github.com/nl-design-system/backlog/issues/39)

**Comment by usethetics** [comment]
Potential variant: (Vertical) task list indicating which steps have been validated (✅), what step is currently being validated (spinner) and which steps still to process.

**Comment by Robbert** [comment]
Definition list and progression lists should be separate components from the text list.

Also interesting to know: `role="list"` is needed for screen readers when `list-style: none` is applied. https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

**Comment by usethetics** [comment]
![Screenshot 2021-01-14 at 09 21 42](https://user-images.githubusercontent.com/248921/104563515-09633f80-564a-11eb-99ed-d9345bb461db.png)
![Screenshot 2021-01-14 at 09 17 23](https://user-images.githubusercontent.com/248921/104563523-0a946c80-564a-11eb-8a56-1f3c9f993142.png)

**Comment by usethetics** [comment]
Ontwerp van gemeente Den Haag voor lijsten:

![image](https://user-images.githubusercontent.com/248921/109626766-39569b80-7b41-11eb-825d-e5ef127884a1.png)
