### ISSUE TITLE
Best Practice: Favicon

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#61]
- [ ] HTML/CSS component
- [ ] Web Component
- [ ] Figma component
- [ ] Design tokens
- [ ] Documentation

# Description

**Comment by Yolijn** [comment]
@Robbert is dit component echt een logische om te delen via NL Design System? Zijn er gedeelde richtlijnen, a11y overwegingen of complexe code?

**Comment by Yolijn** [comment]
As suggested here #135 we probably do not want to include these non-CSS components to the component index although we SHOULD document them somewhere clear
