### ISSUE TITLE
Component: Backlink

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#8]
- [ ] HTML/CSS component
- [ ] Web Component
- [ ] Figma component
- [ ] Design tokens
- [ ] Documentation

**Comment by usethetics** [comment]
First version of Figma component available here: https://www.figma.com/file/gqQhMe3gj4YlC6JrZOWiCv/Components?node-id=0%3A1

**Comment by usethetics** [comment]
Figma component has been updated.

Interactive states of Backlink:

- Default
- Hover
- Focus
- Active
- Disabled

https://www.figma.com/file/gqQhMe3gj4YlC6JrZOWiCv/?node-id=102%3A183
