### ISSUE TITLE
Documentation: Woordenlijst

### ISSUE THREAD

**Issue by usethetics** [nl-design-system/backlog#91]
Als eindgebruiker wil ik dat iedere overheidsuiting de juiste termen gebruikt.

Een woordenlijst zodat iedereen de juiste termen gebruikt en vast leggen wat wel of niet gebruikt wordt. Denk bijvoorbeeld aan BSN of burgerservicenummer.

**Comment by Yolijn** [comment]
Hier willen we als kernteam niet verantwoordelijk voor zijn
